# Generated by Django 3.2.1 on 2021-05-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='QiDian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('author', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('href', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Weibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('jpg', models.CharField(max_length=256)),
            ],
        ),
    ]
