# Generated by Django 3.1.6 on 2021-02-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
