# Generated by Django 3.2.1 on 2021-05-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_qidian_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qidian',
            name='href',
            field=models.CharField(max_length=64),
        ),
    ]
