# Generated by Django 3.2.1 on 2021-05-07 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_qidian_href'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qidian',
            unique_together={('rank', 'title')},
        ),
    ]
