# Generated by Django 3.2.1 on 2021-05-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_qidian_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qidian',
            unique_together=set(),
        ),
    ]
