# Generated by Django 3.2.1 on 2021-05-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_twitter_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter',
            name='content',
            field=models.CharField(max_length=191),
        ),
    ]
