# Generated by Django 3.2.1 on 2021-05-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
