# Generated by Django 3.2.1 on 2021-05-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_login_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
