# Generated by Django 3.2.1 on 2021-05-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('jpg', models.CharField(max_length=256)),
            ],
        ),
    ]
