# Generated by Django 3.2.1 on 2021-05-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_weibo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_detail',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publish',
        ),
        migrations.DeleteModel(
            name='QiDian',
        ),
        migrations.DeleteModel(
            name='Twitter',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='AuthorDetail',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publish',
        ),
    ]
