# Generated by Django 3.2.1 on 2021-05-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_auto_20210511_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='QiDian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('author', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('href', models.CharField(max_length=64)),
            ],
        ),
    ]
